version: "3.8"

services:
  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
      - --web.enable-lifecycle
      - --storage.tsdb.retention.time=15d
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus-data:/prometheus
    restart: unless-stopped
  grafana:
    image: grafana/grafana:11.0.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./grafana-data:/var/lib/grafana
    depends_on:
      - loki
      - tempo
    restart: unless-stopped

  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    command: ["-config.file=/etc/loki/config.yaml"]
    ports:
      - "3100:3100"
    volumes:
      - ./configs/loki.yaml:/etc/loki/config.yaml:ro
      - loki-data:/loki
    restart: unless-stopped

  promtail:
    image: grafana/promtail:3.0.0
    container_name: promtail
    command: ["-config.file=/etc/promtail/config.yaml"]
    # 你的应用日志在 D:\logs\trade-gateway\app.json.log，就用下面这行（Windows 路径要转义）
    volumes:
      - "D:\\logs\\trade-gateway:/host-logs/trade-gateway:ro"
      - ./configs/promtail.yaml:/etc/promtail/config.yaml:ro
    depends_on:
      - loki
    restart: unless-stopped

  tempo:
    image: grafana/tempo:2.4.1
    container_name: tempo
    command: ["-config.file=/etc/tempo/config.yaml"]
    ports:
      - "3200:3200"     # Tempo HTTP
      - "4318:4318"     # OTLP HTTP
      - "4317:4317"     # OTLP gRPC
    volumes:
      - ./configs/tempo.yaml:/etc/tempo/config.yaml:ro
      - tempo-data:/var/tempo
    restart: unless-stopped

volumes:
  loki-data:
  tempo-data:
  prometheus-data:
